[package]
name = "boco_solver"
version = "0.1.0"
authors = ["James Baxter <james.baxter@focusrite.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

petgraph = "0.5.1"